-- Consolidation audit note.
-- The referenced optional notification/preferences tables are not part of the
-- MANOX schema, so this migration intentionally performs no DDL.
-- Existing valid RLS policies remain unchanged.
